# Generated by Django 3.2.6 on 2021-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
