# Generated by Django 3.2.6 on 2021-09-27 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210927_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='CPF deve conter 11 digitos', regex='^.{11}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Telefone deve conter 11 digitos', regex='^.{11}$')]),
        ),
    ]
