# Generated by Django 3.2.6 on 2021-09-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210927_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
