# Generated by Django 3.2.6 on 2021-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hasDebt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
